FinalProject/config/routes.rb
Rails.application.routes.draw do
  resources :amort_rates

  resources :quotes

  resources :vehicle_models

  resources :vehicle_brands

  resources :vehicle_types

  resources :vehicle_colors

  resources :employees

  resources :customers

  resources :statuses

  get 'welcome/home'

  resources :vehicles

  get 'welcome/home'

   root 'welcome#home'

end

FinalProject/app/models/amort_rate.rb
class AmortRate < ActiveRecord::Base
end

FinalProject/app/models/customer.rb
class Customer < ActiveRecord::Base

  belongs_to :quote
  has_one :status
  has_many :vehicles

end

FinalProject/app/models/employee.rb
class Employee < ActiveRecord::Base

belongs_to :quote
end

FinalProject/app/models/quote.rb
class Quote < ActiveRecord::Base

  has_many :employees
  has_many :customers
  has_many :vehicles

end

FinalProject/app/models/status.rb
class Status < ActiveRecord::Base

  belongs_to :customer
end

FinalProject/app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
end

FinalProject/app/models/vehicle_brand.rb
class VehicleBrand < ActiveRecord::Base

  belongs_to :vehicle
  has_many :vehicle_models

end

FinalProject/app/models/vehicle_color.rb
class VehicleColor < ActiveRecord::Base
  belongs_to :vehicle
end

FinalProject/app/models/vehicle_model.rb
class VehicleModel < ActiveRecord::Base

  belongs_to :vehicle
end

FinalProject/app/models/vehicle_type.rb
class VehicleType < ActiveRecord::Base

  belongs_to :vehicle
end

FinalProject/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params[:home]
    end
end

FinalProject/app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:customer_id, :integer, :vehicle_id, :employee_id, :price, :discount, :status, :interest, :months, :principal)
    end
end

FinalProject/app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:year, :vehicle_color_id, :vehicle_type_id, :vehicle_model_id, :vehicle_brand_id, :vin, :price)
    end
end

FinalProject/app/helpers/amort_rates_helper.rb
module AmortRatesHelper
end

FinalProject/app/helpers/application_helper.rb
module ApplicationHelper
end

FinalProject/app/helpers/customers_helper.rb
module CustomersHelper
end

FinalProject/app/helpers/employees_helper.rb
module EmployeesHelper
end

FinalProject/app/helpers/homes_helper.rb
module HomesHelper
end

FinalProject/app/helpers/quotes_helper.rb
module QuotesHelper
end

FinalProject/app/helpers/statuses_helper.rb
module StatusesHelper
end

FinalProject/app/helpers/vehicle_types_helper.rb
module VehicleTypesHelper
end

FinalProject/app/helpers/vehicles_helper.rb
module VehiclesHelper
end

FinalProject/app/helpers/welcome_helper.rb
module WelcomeHelper
end

FinalProject/app/helpers/welcome_pages_helper.rb
module WelcomePagesHelper
end

FinalProject/app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% @vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :vehicle_color_id %><br>
    <%= f.number_field :vehicle_color_id %>
  </div>
  <div class="field">
    <%= f.label :vehicle_type_id %><br>
    <%= f.number_field :vehicle_type_id %>
  </div>
  <div class="field">
    <%= f.label :vehicle_model_id %><br>
    <%= f.number_field :vehicle_model_id %>
  </div>
  <div class="field">
    <%= f.label :vehicle_brand_id %><br>
    <%= f.number_field :vehicle_brand_id %>
  </div>
  <div class="field">
    <%= f.label :vin %><br>
    <%= f.text_field :vin %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

FinalProject/app/views/vehicles/edit.html.erb
<h1>Editing vehicle</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

FinalProject/app/views/vehicles/index.html.erb
<h1>Listing vehicles</h1>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th>Vehicle color</th>
      <th>Vehicle type</th>
      <th>Vehicle model</th>
      <th>Vehicle brand</th>
      <th>Vin</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.year %></td>
        <td><%= vehicle.vehicle_color_id %></td>
        <td><%= vehicle.vehicle_type_id %></td>
        <td><%= vehicle.vehicle_model_id %></td>
        <td><%= vehicle.vehicle_brand_id %></td>
        <td><%= vehicle.vin %></td>
        <td><%= vehicle.price %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %>

FinalProject/app/views/vehicles/new.html.erb
<h1>New vehicle</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicles_path %>

FinalProject/app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @vehicle.year %>
</p>

<p>
  <strong>Vehicle color:</strong>
  <%= @vehicle.vehicle_color_id %>
</p>

<p>
  <strong>Vehicle type:</strong>
  <%= @vehicle.vehicle_type_id %>
</p>

<p>
  <strong>Vehicle model:</strong>
  <%= @vehicle.vehicle_model_id %>
</p>

<p>
  <strong>Vehicle brand:</strong>
  <%= @vehicle.vehicle_brand_id %>
</p>

<p>
  <strong>Vin:</strong>
  <%= @vehicle.vin %>
</p>

<p>
  <strong>Price:</strong>
  <%= @vehicle.price %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>