FinalProject/config/routes.rb
Rails.application.routes.draw do
  resources :amort_rates

  resources :quotes

  resources :vehicle_models

  resources :vehicle_brands

  resources :vehicle_types

  resources :vehicle_colors

  resources :employees

  resources :customers

  resources :statuses

  get 'welcome/home'

  resources :vehicles

  get 'welcome/home'

   root 'welcome#home'

end

FinalProject/app/models/amort_rate.rb
class AmortRate < ActiveRecord::Base
end

FinalProject/app/models/customer.rb
class Customer < ActiveRecord::Base

  belongs_to :quote
  has_one :status
  has_many :vehicles

end

FinalProject/app/models/employee.rb
class Employee < ActiveRecord::Base

belongs_to :quote
end

FinalProject/app/models/quote.rb
class Quote < ActiveRecord::Base

  has_many :employees
  has_many :customers
  has_many :vehicles

end

FinalProject/app/models/status.rb
class Status < ActiveRecord::Base

  belongs_to :customer
end

FinalProject/app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
end

FinalProject/app/models/vehicle_brand.rb
class VehicleBrand < ActiveRecord::Base

  belongs_to :vehicle
  has_many :vehicle_models

end

FinalProject/app/models/vehicle_color.rb
class VehicleColor < ActiveRecord::Base
  belongs_to :vehicle
end

FinalProject/app/models/vehicle_model.rb
class VehicleModel < ActiveRecord::Base

  belongs_to :vehicle
end

FinalProject/app/models/vehicle_type.rb
class VehicleType < ActiveRecord::Base

  belongs_to :vehicle
end

FinalProject/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params[:home]
    end
end

FinalProject/app/controllers/vehicle_models_controller.rb
class VehicleModelsController < ApplicationController
  before_action :set_vehicle_model, only: [:show, :edit, :update, :destroy]

  # GET /vehicle_models
  # GET /vehicle_models.json
  def index
    @vehicle_models = VehicleModel.all
  end

  # GET /vehicle_models/1
  # GET /vehicle_models/1.json
  def show
  end

  # GET /vehicle_models/new
  def new
    @vehicle_model = VehicleModel.new
  end

  # GET /vehicle_models/1/edit
  def edit
  end

  # POST /vehicle_models
  # POST /vehicle_models.json
  def create
    @vehicle_model = VehicleModel.new(vehicle_model_params)

    respond_to do |format|
      if @vehicle_model.save
        format.html { redirect_to @vehicle_model, notice: 'Vehicle model was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle_model }
      else
        format.html { render :new }
        format.json { render json: @vehicle_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicle_models/1
  # PATCH/PUT /vehicle_models/1.json
  def update
    respond_to do |format|
      if @vehicle_model.update(vehicle_model_params)
        format.html { redirect_to @vehicle_model, notice: 'Vehicle model was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle_model }
      else
        format.html { render :edit }
        format.json { render json: @vehicle_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicle_models/1
  # DELETE /vehicle_models/1.json
  def destroy
    @vehicle_model.destroy
    respond_to do |format|
      format.html { redirect_to vehicle_models_url, notice: 'Vehicle model was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle_model
      @vehicle_model = VehicleModel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_model_params
      params.require(:vehicle_model).permit(:model, :vehicle_brand_id)
    end
end

FinalProject/app/helpers/amort_rates_helper.rb
module AmortRatesHelper
end

FinalProject/app/helpers/application_helper.rb
module ApplicationHelper
end

FinalProject/app/helpers/customers_helper.rb
module CustomersHelper
end

FinalProject/app/helpers/employees_helper.rb
module EmployeesHelper
end

FinalProject/app/helpers/homes_helper.rb
module HomesHelper
end

FinalProject/app/helpers/quotes_helper.rb
module QuotesHelper
end

FinalProject/app/helpers/statuses_helper.rb
module StatusesHelper
end

FinalProject/app/helpers/vehicle_models_helper.rb
module VehicleModelsHelper
end

FinalProject/app/helpers/vehicle_types_helper.rb
module VehicleTypesHelper
end

FinalProject/app/helpers/vehicles_helper.rb
module VehiclesHelper
end

FinalProject/app/helpers/welcome_helper.rb
module WelcomeHelper
end

FinalProject/app/views/vehicle_models/_form.html.erb
<%= form_for(@vehicle_model) do |f| %>
  <% if @vehicle_model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle_model.errors.count, "error") %> prohibited this vehicle_model from being saved:</h2>

      <ul>
      <% @vehicle_model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :vehicle_brand_id %><br>
    <%= f.number_field :vehicle_brand_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

FinalProject/app/views/vehicle_models/edit.html.erb
<h1>Editing vehicle_model</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehicle_model %> |
<%= link_to 'Back', vehicle_models_path %>

FinalProject/app/views/vehicle_models/index.html.erb
<h1>Listing vehicle_models</h1>

<table>
  <thead>
    <tr>
      <th>Model</th>
      <th>Vehicle brand</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicle_models.each do |vehicle_model| %>
      <tr>
        <td><%= vehicle_model.model %></td>
        <td><%= vehicle_model.vehicle_brand_id %></td>
        <td><%= link_to 'Show', vehicle_model %></td>
        <td><%= link_to 'Edit', edit_vehicle_model_path(vehicle_model) %></td>
        <td><%= link_to 'Destroy', vehicle_model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle model', new_vehicle_model_path %>

FinalProject/app/views/vehicle_models/new.html.erb
<h1>New vehicle_model</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicle_models_path %>

FinalProject/app/views/vehicle_models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Model:</strong>
  <%= @vehicle_model.model %>
</p>

<p>
  <strong>Vehicle brand:</strong>
  <%= @vehicle_model.vehicle_brand_id %>
</p>

<%= link_to 'Edit', edit_vehicle_model_path(@vehicle_model) %> |
<%= link_to 'Back', vehicle_models_path %>