FinalProject/config/routes.rb
Rails.application.routes.draw do
  resources :amort_rates

  resources :quotes

  resources :vehicle_models

  resources :vehicle_brands

  resources :vehicle_types

  resources :vehicle_colors

  resources :employees

  resources :customers

  resources :statuses

  get 'welcome/home'

  resources :vehicles

  get 'welcome/home'

   root 'welcome#home'

end

FinalProject/app/models/amort_rate.rb
class AmortRate < ActiveRecord::Base
end

FinalProject/app/models/customer.rb
class Customer < ActiveRecord::Base

  belongs_to :quote
  has_one :status
  has_many :vehicles

end

FinalProject/app/models/employee.rb
class Employee < ActiveRecord::Base

belongs_to :quote
end

FinalProject/app/models/quote.rb
class Quote < ActiveRecord::Base

  has_many :employees
  has_many :customers
  has_many :vehicles

end

FinalProject/app/models/status.rb
class Status < ActiveRecord::Base

  belongs_to :customer
end

FinalProject/app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
end

FinalProject/app/models/vehicle_brand.rb
class VehicleBrand < ActiveRecord::Base

  belongs_to :vehicle
  has_many :vehicle_models

end

FinalProject/app/models/vehicle_color.rb
class VehicleColor < ActiveRecord::Base
  belongs_to :vehicle
end

FinalProject/app/models/vehicle_model.rb
class VehicleModel < ActiveRecord::Base

  belongs_to :vehicle
end

FinalProject/app/models/vehicle_type.rb
class VehicleType < ActiveRecord::Base

  belongs_to :vehicle
end

FinalProject/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params[:home]
    end
end

FinalProject/app/controllers/vehicle_types_controller.rb
class VehicleTypesController < ApplicationController
  before_action :set_vehicle_type, only: [:show, :edit, :update, :destroy]

  # GET /vehicle_types
  # GET /vehicle_types.json
  def index
    @vehicle_types = VehicleType.all
  end

  # GET /vehicle_types/1
  # GET /vehicle_types/1.json
  def show
  end

  # GET /vehicle_types/new
  def new
    @vehicle_type = VehicleType.new
  end

  # GET /vehicle_types/1/edit
  def edit
  end

  # POST /vehicle_types
  # POST /vehicle_types.json
  def create
    @vehicle_type = VehicleType.new(vehicle_type_params)

    respond_to do |format|
      if @vehicle_type.save
        format.html { redirect_to @vehicle_type, notice: 'Vehicle type was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle_type }
      else
        format.html { render :new }
        format.json { render json: @vehicle_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicle_types/1
  # PATCH/PUT /vehicle_types/1.json
  def update
    respond_to do |format|
      if @vehicle_type.update(vehicle_type_params)
        format.html { redirect_to @vehicle_type, notice: 'Vehicle type was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle_type }
      else
        format.html { render :edit }
        format.json { render json: @vehicle_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicle_types/1
  # DELETE /vehicle_types/1.json
  def destroy
    @vehicle_type.destroy
    respond_to do |format|
      format.html { redirect_to vehicle_types_url, notice: 'Vehicle type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle_type
      @vehicle_type = VehicleType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_type_params
      params.require(:vehicle_type).permit(:type)
    end
end

FinalProject/app/helpers/amort_rates_helper.rb
module AmortRatesHelper
end

FinalProject/app/helpers/application_helper.rb
module ApplicationHelper
end

FinalProject/app/helpers/customers_helper.rb
module CustomersHelper
end

FinalProject/app/helpers/employees_helper.rb
module EmployeesHelper
end

FinalProject/app/helpers/homes_helper.rb
module HomesHelper
end

FinalProject/app/helpers/quotes_helper.rb
module QuotesHelper
end

FinalProject/app/helpers/statuses_helper.rb
module StatusesHelper
end

FinalProject/app/helpers/vehicle_types_helper.rb
module VehicleTypesHelper
end

FinalProject/app/helpers/vehicles_helper.rb
module VehiclesHelper
end

FinalProject/app/helpers/welcome_helper.rb
module WelcomeHelper
end

FinalProject/app/views/vehicle_types/_form.html.erb
<%= form_for(@vehicle_type) do |f| %>
  <% if @vehicle_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle_type.errors.count, "error") %> prohibited this vehicle_type from being saved:</h2>

      <ul>
      <% @vehicle_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

FinalProject/app/views/vehicle_types/edit.html.erb
<h1>Editing vehicle_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehicle_type %> |
<%= link_to 'Back', vehicle_types_path %>

FinalProject/app/views/vehicle_types/index.html.erb
<h1>Listing vehicle_types</h1>
<p id="notice"><%= notice %></p>
<table>
  <td><%= link_to 'Colors', vehicle_types_path %></td>
  <td><%= link_to 'Makes', vehicle_models_path %></td>
  <td><%= link_to 'Models', vehicle_brands_path %></td>
</table>
<table>
  <thead>
    <tr>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicle_types.each do |vehicle_type| %>
      <tr>
        <td><%= vehicle_type.type %></td>
        <td><%= link_to 'Show', vehicle_type %></td>
        <td><%= link_to 'Edit', edit_vehicle_type_path(vehicle_type) %></td>
        <td><%= link_to 'Destroy', vehicle_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle type', new_vehicle_type_path %>

FinalProject/app/views/vehicle_types/new.html.erb
<h1>New vehicle_type</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicle_types_path %>

FinalProject/app/views/vehicle_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @vehicle_type.type %>
</p>

<%= link_to 'Edit', edit_vehicle_type_path(@vehicle_type) %> |
<%= link_to 'Back', vehicle_types_path %>